In [1]:
import numpy as np

def producto_escalar():

    n = int(input("Ingrese la longitud de los vectores (CM): "))

    vector_a = np.random.randint(-10, 10, n)
    vector_b = np.random.randint(-10, 10, n)

    producto = np.dot(vector_a, vector_b)

    print(f"\nVector A: {vector_a}")
    print(f"Vector B: {vector_b}")
    print(f"Producto escalar: {producto}")

producto_escalar()

Ingrese la longitud de los vectores: 35

Vector A: [ 4 -2  9 -2 -9 -7  7  2  1  0  5 -9 -7  6 -9 -1 -6 -1  9 -9  7 -1 -2 -1
  2 -8 -2  3 -4 -9 -3  4 -1 -7  5]
Vector B: [ -8   3  -4   1  -6  -8  -1  -1  -5  -7   2 -10  -9   5   9   1  -6  -3
   1   1   9  -7   9   0  -4   8   5  -2  -9  -9 -10  -5   6  -9   7]
Producto escalar: 353


In [2]:
import numpy as np

def generar_dimensiones():
    """Genera dimensiones aleatorias entre 2 y 8 asegurando compatibilidad."""
    filas_a = np.random.randint(2, 9)
    columnas_a = np.random.randint(2, 9)

    if operacion == 'suma':
        filas_b, columnas_b = filas_a, columnas_a
    else:
        filas_b, columnas_b = columnas_a, np.random.randint(2, 9)

    return filas_a, columnas_a, filas_b, columnas_b

def generar_matriz(filas, columnas):
    """Genera una matriz con números enteros aleatorios entre -10 y 10."""
    return np.random.randint(-10, 10, (filas, columnas))

operacion = input("Seleccione una operación (suma/multiplicación): ").strip().lower()
while operacion not in ['suma', 'multiplicacion']:
    operacion = input("Operación inválida. Escriba 'suma' o 'multiplicación': ").strip().lower()

filas_a, columnas_a, filas_b, columnas_b = generar_dimensiones()

A = generar_matriz(filas_a, columnas_a)
B = generar_matriz(filas_b, columnas_b)

if operacion == 'suma':
    resultado = A + B
    print(f"\nMatriz A ({filas_a}x{columnas_a}):\n{A}")
    print(f"\nMatriz B ({filas_b}x{columnas_b}):\n{B}")
    print(f"\nSuma de matrices:\n{resultado}")
else:
    resultado = np.dot(A, B)
    print(f"\nMatriz A ({filas_a}x{columnas_a}):\n{A}")
    print(f"\nMatriz B ({filas_b}x{columnas_b}):\n{B}")
    print(f"\nMultiplicación de matrices:\n{resultado}")


Seleccione una operación (suma/multiplicación): suma

Matriz A (8x3):
[[ 8 -3 -9]
 [-2  8  3]
 [-8 -5  8]
 [ 6 -9  7]
 [ 5 -9 -9]
 [-6  3  1]
 [ 5 -4  9]
 [-4  4  4]]

Matriz B (8x3):
[[ -3  -2  -6]
 [  7   2 -10]
 [  5   0  -1]
 [ -8   9 -10]
 [  0  -9   4]
 [ -6   6   6]
 [  6   8   7]
 [  1  -2   5]]

Suma de matrices:
[[  5  -5 -15]
 [  5  10  -7]
 [ -3  -5   7]
 [ -2   0  -3]
 [  5 -18  -5]
 [-12   9   7]
 [ 11   4  16]
 [ -3   2   9]]
